version: "3.7"

services:
  nginx:
    build: ./nginx
    image: nginx_proxy:0.1.0
    restart: always
    networks:
      - network
    ports:
      - 80:80
    volumes:
      - ./nginx_log:/var/log/nginx
    depends_on:
      - app

  app:
    image: <app-image> #! version up!
    restart: always
    networks:
      - network
    ports:
      - 5500:5500
    env_file:
      - ./.env

  db:
    image: postgres:9.6.23
    restart: always
    networks:
      - network
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    networks:
      - network
    env_file:
      - ./.env
    ports:
      - 5555:80
    depends_on:
      - db

networks:
  network: {}
