name: CD workflow 0.0.1 #! version up!

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: CHECK ROOT PATH
        run: ls -a
      - name: DOCKER VERSION CHECK
        run: docker --version
      # ...
